# username: admin
# password: admin
# https://github.com/grafana/docker-otel-lgtm
services:
  otel:
    image: grafana/otel-lgtm:${GRAFANA_OTEL_VERSION:-latest}
    ports:
      - ${GRAFANA_PORT:-3000}:3000
      - 4317:4317 # OTLP/GRPC
      - 4318:4318 # OTLP/HTTP
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
