services:
  # https://github.com/AdguardTeam/AdGuardHome
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    pull_policy: always
    expose:
      - 3000
      - 80
      - 53
    ports:
      - ${ADGUARD_CONFIG_PORT:-5001}:3000 # Config UI, Use this port to configure AdGuard Home
      - ${ADGUARD_PORT:-5000}:80 # AdGuard Admin UI
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - work:/opt/adguardhome/work
      - conf:/opt/adguardhome/conf
    restart: unless-stopped
    networks:
      - adguard

networks:
  adguard:
    name: adguard
    driver: bridge

volumes:
  work:
  conf:
