services:
  portainer:
    image: portainer/portainer-ce:${PORTAINER_VERSION:-latest}
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ${PORTAINER_PORT:-9000}:9000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  portainer:
