services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    pull_policy: always
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000
    restart: unless-stopped

volumes:
  portainer:
    name: portainer
