services:
  mysql:
    image: mysql:latest
    container_name: mysql
    pull_policy: always
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - mysql
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    pull_policy: always
    depends_on:
      - mysql
    restart: unless-stopped
    ports:
      - 8053:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - mysql

networks:
  mysql:
    name: mysql
    driver: bridge

volumes:
  mysql:
    name: mysql-db
