services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    depends_on:
      - postgres
    restart: unless-stopped
    ports:
      - 8054:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@email.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_DISABLE_POSTFIX: 1
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - postgres

volumes:
  postgres:
    name: postgres-db
  pgadmin:
    name: pgadmin-data

networks:
  postgres:
    name: postgres
    driver: bridge
