services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    ports:
      - 27017:27017
    networks:
      - mongo
    volumes:
      - mongo:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8052:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - mongo

networks:
  mongo:
    name: mongo
    driver: bridge

volumes:
  mongo:
    name: mongo-db
