services:
  redis:
    image: redis:alpine
    container_name: redis
    pull_policy: always
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3
    ports:
      - 6379:6379
    volumes:
      - data:/data
    networks:
      - redis

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: commander
    pull_policy: always
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - ${REDIS_COMMANDER_PORT:-8081}:8081
    networks:
      - redis
    depends_on:
      - redis

volumes:
  data:
    name: redis-data

networks:
  redis:
    name: redis
    driver: bridge
