services:
  redis:
    image: redis:${REDIS_VERSION:-latest}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - redis

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - ${REDIS_COMMANDER_PORT:-8081}:8081
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - redis

volumes:
  redis:

networks:
  redis:
    name: redis
    driver: bridge
